"""
AI Quiz & Mock Interview - Flask Application Entry Point.

Run with:  python app.py
"""
import os
from flask import Flask, render_template
from flask_login import LoginManager

from config import Config
from models import db, bcrypt, User


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Ensure database directory exists (for SQLite)
    db_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'database')
    os.makedirs(db_dir, exist_ok=True)

    # Initialize extensions
    db.init_app(app)
    bcrypt.init_app(app)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'
    login_manager.login_message = 'Please log in to access this page.'
    login_manager.login_message_category = 'info'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    # Register blueprints
    from routes.auth import auth_bp
    from routes.dashboard import dashboard_bp
    from routes.quiz import quiz_bp
    from routes.interview import interview_bp
    from routes.performance import performance_bp
    from routes.history import history_bp
    from routes.profile import profile_bp

    app.register_blueprint(auth_bp)
    app.register_blueprint(dashboard_bp)
    app.register_blueprint(quiz_bp)
    app.register_blueprint(interview_bp)
    app.register_blueprint(performance_bp)
    app.register_blueprint(history_bp)
    app.register_blueprint(profile_bp)

    # Make Gemini configuration status available to every template so the
    # UI can show an explicit "Demo mode" banner instead of leaving it to
    # be silently inferred from question text.
    @app.context_processor
    def inject_gemini_status():
        return {'gemini_configured': bool((app.config.get('GEMINI_API_KEY') or '').strip())}

    # Public landing page
    @app.route('/')
    def index():
        return render_template('index.html')

    # Error handlers
    @app.errorhandler(404)
    def not_found(e):
        return render_template('errors/404.html'), 404

    @app.errorhandler(403)
    def forbidden(e):
        return render_template('errors/403.html'), 403

    @app.errorhandler(500)
    def server_error(e):
        return render_template('errors/500.html'), 500

    # Create tables on first run
    with app.app_context():
        db.create_all()

    # Loud, unmissable startup log so it's obvious which mode Gemini is in.
    # This is the #1 cause of "it still shows demo questions after I added a
    # key": the key never actually reached app.config (wrong .env path,
    # typo'd variable name, server not restarted after editing .env, etc.)
    # and that fact was previously only a quiet log line buried in warnings.
    key = (app.config.get('GEMINI_API_KEY') or '').strip()
    if key:
        masked = key[:4] + '...' + key[-4:] if len(key) > 8 else '****'
        app.logger.warning(
            f"[Gemini] API key detected ({masked}), model="
            f"'{app.config.get('GEMINI_MODEL')}'. LIVE mode: quiz/interview "
            f"content will be generated by Gemini."
        )
    else:
        app.logger.warning(
            "[Gemini] No GEMINI_API_KEY found in app.config. DEMO mode: "
            "quiz/interview content will be placeholder text, not real AI "
            "output. If you added a key and still see this, check: "
            "(1) the .env file sits next to app.py/config.py, "
            "(2) the variable is spelled exactly 'GEMINI_API_KEY', "
            "(3) you fully restarted the Flask process (editing .env alone "
            "does not trigger the debug reloader), "
            "(4) there are no quotes/extra spaces around the value."
        )

    return app


app = create_app()

if __name__ == '__main__':
    app.run(debug=app.config.get('DEBUG', True), host='0.0.0.0', port=5000)
